### ISSUE TITLE
Spike: Figure out how to alert sources-api about bad ARN auths.

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#649]
In GitLab by @infinitewarp on Feb 26, 2020, 10:23

Problem: We currently attempt to verify permissions of incoming ARNs, but we believe the intent is for us to blindly trust input from sources-api and notify it via some mechanism if/when we encounter problems with a particular authentication. As of [As a user I want my Clount to be updated when I update my Sources Authentication](https://gitlab.com/cloudigrade/cloudigrade/issues/640), we may be introducing inconsistency with how we enforce our verification.

Desired output: A definition of what should be our best practice going forward. If this involves reaching back to sources-api, ideally the definition includes some sample code.

Consider the following: What if in the not-too-distant future sources *actually* supports multiple applications sharing the same authentication, which is what they designed for in the first place. What would be desired if Cloud Meter shares an authentication with Cost Management, and their verification passes and our verification fails?

Options to consider:
- We always verify. We cannot rely on anyone else verifying what we need. sources-api specifically **is not designed to support active auth verification**.
- We always verify, we do not save new ARNs if they don't verify.
- We always verify, we blindly save new ARNs even if they don't verify.
- We always verify, we do not save changed ARNs but we delete the old ARN's data if the new one doesn't verify.
- We always verify, we blindly save changed ARNs and delete old even if the new one doesn't verify.
- We mark the sources-api authentication as "unavailable" if verification fails.
- We do not mark the sources-api authentication as "unavailable" if verification fails, but use some other API to notify sources that something bad happened.

Time box: 3 active days, understanding that there may be async communication delays.

**Comment by katherine-black** [comment]
In GitLab by @werwty on Feb 27, 2020, 15:39

We need to keep our Cloud Account Model aligned with sources. Because when sources prompt us to do an availability check, we need the stored authentication to do so.

### Source Create

When we get a sources create message:

- If the arn passes verification:
   - Create a clount
   - Configure cloudtrail
   - Do initial describe
   - update Authentication and Application (if applicable) availability_status in Sources.
- If the arn does not pass verification
   - Still create a clount, but mark it as disabled.
   - Do not configure cloudtrail
   - Do not do the initial describe.
   - update Authentication and Application (if applicable) availability_status in Sources.

### Sources-Monitor Availability Check

Sources-monitor will kick off an availability_check on unavailable sources that occurs every ~30 minutes.

TODO: Check to see if this is also the case for partially available sources.

This availability_check will send a POST request to some cloudmeter endpoint. We tell Sources what this endpoint is with an environment variable CLOUD_METER_AVAILABILITY_CHECK_URL in e2e.
The expected payload of this check will be `{"source_id": "1234"}`

When we receive this call, we will identify the clount with the matching source_id and verify the arn. 

Two possible things might happen:

1. Unavailable Source is still unavailable. We do nothing
2. Unavailable Source is now available.
    - Mark Clount as enabled.
    - update Authentication and Application (if applicable) availability_status in Sources.
    - If we have not configured cloudtrail for user, do so.
    - If we have not ran initial describe instances, do so.

### Sources Authentication Update

In the case that a user updates their ARN we should always change the ARN stored in our system.

- If new AWS account: Disable old account's cloudtrail
- If the arn passes verification:
   - If new AWS account: Configure cloudtrail
   - If new AWS account: Do initial describe 
   - update Authentication and Application (if applicable) availability_status in Sources.
- If the arn does not pass verification
   - Mark Clount as disabled.
   - update Authentication and Application (if applicable) availability_status in Sources.

Here's a jupyter notebook that shows how to patch an Authentication and Application. [644-sources-availability.ipynb](/uploads/876544226cf9c6b900f2bfb3c3e7695a/644-sources-availability.ipynb)

### TODO:

- [x] File story to create a new availability_check endpoint for cloudmeter.
- [X] File story to implement a way to disable an account.
- [x] File story to implement the availability check logic described above.


Regarding the "Consider the following": It shouldn't be too much of a problem. The sources UI looks at both authentication availability and application availability to determine if a source is `available`, `unavailable` or `partially available`. In the costmgmt vs cloudigrade case, this source should show as `partially available`

I do not think we can tell the difference between an available source becoming unavailable, and the user no longer launching instances. Right now we don't have the cron check for this. There is a story https://gitlab.com/cloudigrade/cloudigrade/issues/547 filed for this, update the story so that the following it done:

- If available Source is now unavailable
    - Mark Clount as disabled
    - Update Authentication and Application (if applicable) availability_status in Sources.


### Other Questions

Should we remove the uniqueness constraint on `aws_account_id`? Sources does allow a user to create more than one arn with the same account_id. Maybe we can create a separate Clount for each of these but disable every clount after the first, and write some "Duplicate Account" message to the availability status.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Feb 28, 2020, 10:05

Great research findings! Since we discussed this after standup and agreed on the proposed path forward, I'm now closing this issue.

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Feb 28, 2020, 10:05

closed
